### PR TITLE
Dockerized critter

### PR DESCRIPTION
**Pull request by pvdissel**
Add Dockerfile to dockerize Critter and adjusted the packaging files to work nicely in a docker container

### CODE REVIEW

**Comment by pvdissel** [comment]
Failed because it seems to need authorization to fetch the selfdiagnose dependency, not something I touched in this PR:
```
[ERROR] Failed to execute goal on project critter: Could not resolve dependencies for project com.philemonworks:critter:jar:1.0.2: Failed to collect dependencies at com.philemonworks:selfdiagnose:jar:2.5.1: Failed to read artifact descriptor for com.philemonworks:selfdiagnose:jar:2.5.1: Could not transfer artifact com.philemonworks:selfdiagnose:pom:2.5.1 from/to emicklei-repo (http://emicklei.googlecode.com/svn/repo): Not authorized , ReasonPhrase:Authorization Required. -> [Help 1]
```

**Comment by emicklei** [comment]
Google no longer supports binary downloads from their repositories. I have to find another place for them; probably maven central.

**Comment by pvdissel** [comment]
Bintray is super easy to use:
https://bintray.com
And it's growing in popularity over Maven Central

**Comment by emicklei** [comment]
Thx,  so I setup a maven repo and added the lastest artifact 2.5.9.
But looking at the download url, I wonder what the repo url must be to put in the pom of critter

My guess: https://bintray.com/artifact/download/emicklei/maven
```
https://bintray.com/artifact/download/emicklei/maven/com/philemonworks/selfdiagnose/2.5.9/selfdiagnose-2.5.9.jar
```

**Comment by pvdissel** [comment]
Almost:
```
http://dl.bintray.com/emicklei/maven
```

You can find this by:
- Going to https://bintray.com/emicklei/maven
- Click the "Set me up!" on the right
- Open the "Downloading" dropdown
- Open the "Using Maven with this repository" dropdown
- Click the "Resolving artifacts using Maven" link
- And then you're presented with the maven url info

You can also include your repository into the Bintray JCenter repo:
- https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinacentralrepository.html

And even include it into Maven Central, if you want to do the initial hassle on the Maven Central side:
- https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

**Pull request merged**
